FROM node:18-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

ARG MONGO_USERNAME
ARG MONGO_PASSWORD
ARG MONGO_PORT
ARG MONGO_HOST
ARG MONGO_DB_NAME
ARG PORT
ARG NODE_ENV

ENV MONGO_USERNAME=$MONGO_USERNAME \
    MONGO_PASSWORD=$MONGO_PASSWORD \
    MONGO_PORT=$MONGO_PORT \
    MONGO_HOST=$MONGO_HOST \
    MONGO_DB_NAME=$MONGO_DB_NAME \
    PORT=$PORT \
    NODE_ENV=$NODE_ENV
EXPOSE $PORT
ENTRYPOINT ["npm", "run"]
CMD ["start"]